---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  #system: bindep.txt

ansible_config: 'ansible.cfg'

additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - RUN /usr/bin/python3 -m pip install --upgrade pip
    - COPY --from=quay.io/project-receptor/receptor:0.9.7 /usr/bin/receptor /usr/bin/receptor
    - RUN chown 1000:1000 /home/runner
    - RUN mkdir -p /var/run/receptor
    - ADD run.sh /run.sh
    - CMD /run.sh
    - USER 1000
    - RUN git lfs install
